Model:
  num_frames: 8
  crop_size: 128
  work_with_crop: True
  batch_size: 16
  epochs: 20
  save_every: 10
  optimizer:
    name: Adam
    lr: 1e-3
    lr_schedule:
      type: StepLR
      params:
        step_size: 1
        milestones: [150, 400, 450]
        gamma: 0.1
data_path:
  path: '/home/george/PycharmProjects/Combining-segmentation-and-Inpainting/output'
logs_dir: './logs'
working_dir: './results'