Model:
  num_frames: 8
  crop_size: 64
  work_with_crop: True
  batch_size: 4
  epochs: 1000
  save_every: 100
  optimizer:
    name: Adam
    lr: 1e-3
    lr_schedule:
      type: StepLR
      params:
        step_size: 0.3
        milestones: [150, 400, 450]
        gamma: 0.1
